services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: wb-backend-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WB_Database
  backend-express:
    build: 
      context: ./WaveBrigade-backend
      dockerfile: Dockerfile
    container_name: wb-backend-express
    depends_on:
      - database
      - backend-grpc
    volumes:
      - ./WaveBrigade-backend/server:/app/backend/server
  backend-grpc:
    build:
      context: ./grpc
      dockerfile: Dockerfile
    container_name: wb-backend-grpc
  joiner-frontend:
    build:
      context: ./WaveBrigade-frontend
      dockerfile: deployment.Dockerfile
    container_name: wb-joiner-frontend
    volumes:
      - ./WaveBrigade-frontend/src:/app/joiner/frontend/src
    environment:
      - BACKEND_PATH=https://rsjwavebrigade.com/backend
      - BACKEND_SOCKET=https://rsjwavebrigade.com
    depends_on:
      - database 
      - backend-express
      - backend-grpc
  nginx:
    container_name: wb-nginx
    image: nginx:latest
    ports:
        - 8081:80
        - 4431:443
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./certs:/etc/nginx/ssl
    depends_on:
      - backend-express 
      - database
      - backend-grpc
      - joiner-frontend