# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emotiBits.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'emotiBits.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65motiBits.proto\x12\temotiBits\"$\n\x06\x44\x65vice\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"$\n\rDeviceRequest\x12\x13\n\x0bsessionName\x18\x01 \x01(\t\"3\n\nDeviceList\x12%\n\nallDevices\x18\x01 \x03(\x0b\x32\x11.emotiBits.Device2\x88\x01\n\x0b\x66indDevices\x12:\n\ngetDevices\x12\x11.emotiBits.Device\x1a\x15.emotiBits.DeviceList(\x01\x30\x01\x12=\n\x0c\x66oundDevices\x12\x18.emotiBits.DeviceRequest\x1a\x11.emotiBits.Device0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotiBits_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICE']._serialized_start=30
  _globals['_DEVICE']._serialized_end=66
  _globals['_DEVICEREQUEST']._serialized_start=68
  _globals['_DEVICEREQUEST']._serialized_end=104
  _globals['_DEVICELIST']._serialized_start=106
  _globals['_DEVICELIST']._serialized_end=157
  _globals['_FINDDEVICES']._serialized_start=160
  _globals['_FINDDEVICES']._serialized_end=296
# @@protoc_insertion_point(module_scope)
