const CLIENT_SOCKET_ASSIGNMENT = "CLIENT_SOCKET_ASSIGNMENT";
const START_DEVICE_DISCOVERY = "START_DEVICE_DISCOVERY"
const WAITING_ROOM_PULSE = "WAITING_ROOM_PULSE";

const DEVICE_REGISTRATION_PULSE = "DEVICE_REGISTRATION_PULSE";
const NEW_DEVICE_DISCOVERED = "NEW_DEVICE_DISCOVERED";
const NEW_USER_JOINER = "NEW_USER_JOINER";
const SESSION_CONFIGURATION_CHANGE = "SESSION_CONFIGURATION_CHANGE";